/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlurReveal: typeof import('./components/blurReveal/index.vue')['default']
    BoxReveal: typeof import('./components/boxReveal/index.vue')['default']
    Globe: typeof import('./components/globe/index.vue')['default']
    MyFooter: typeof import('./components/myFooter/index.vue')['default']
    MyHead: typeof import('./components/myHead/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const BlurReveal: typeof import('./components/blurReveal/index.vue')['default']
  const BoxReveal: typeof import('./components/boxReveal/index.vue')['default']
  const Globe: typeof import('./components/globe/index.vue')['default']
  const MyFooter: typeof import('./components/myFooter/index.vue')['default']
  const MyHead: typeof import('./components/myHead/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}